### ISSUE TITLE
Add more drivers

### ISSUE THREAD

**Issue by PietroCampana** [biqute/qinst#7]
- [x] SIM928 isolated voltage source
- [x] Keithley 6514 pico-amperometer
- [ ] Keithley 2231A DC source

**Comment by marcogobbo** [comment]
- [ ] N9916A FieldFox Handheld Microwave Analyzer by Keysight
- [ ] R&S SMA100B RF and microwave signal generator by Rohde & Schwarz.

**Comment by rodolfocarobene** [comment]
R&S SMA100B RF and microwave signal generator by Rohde & Schwarz.

- minimo 8kHz, massimo 20 GHz (per tutte le frequenze, anche offset)
- getter fase
- f_mul (da -10_000 a 10_000)
- mode sweep in auto
